name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12.8"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .

      - name: Install test dependencies
        run: pip install pytest pytest-cov coverage

      - name: Run tests with coverage for assignment 1
        run: pytest Assignment-1 -v --cov=Assignment-1 --cov-report=xml --cov-report=html

      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true

      - name: Run tests with coverage for assignment 2
        run: pytest Assignment-2 -v --cov=Assignment-2 --cov-report=xml --cov-report=html

      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true

      - name: Install dependencies
        run: pip install -e Assignment-3/Part-3/finite-element-analysis

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install mesa
  
      - name: Run tests with coverage for assignment 3 Part 3
        run: pytest Assignment-3/Part-3 -v --cov=Assignment-3/Part-3 --cov-report=xml --cov-report=html

      - name: Run tests with coverage for assignment 3 Part 4
        run: pytest Assignment-3/Part-4 -v --cov=Assignment-3/Part-4 --cov-report=xml --cov-report=html

      - name: Run tests with coverage for assignment 4
        run: pytest Assignment-4 -v --cov=Assignment-4 --cov-report=xml --cov-report=html

      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true